// frontend/src/dashboard.tsx
import style from './dashboard.module.scss';
import OverAllGraph from './graph-overall/view';
import { IData } from './graph-overall/data.interface.ts';
import { ILegend } from './graph-overall/legend.interface.ts';
import BotSummary from './bot-summary-panel/view';

import { Bot } from './rpc/bot_pb';

function Dashboard() {

  const legend: ILegend[] = [
    {
      name: 'Hodl BTC Profit',
      valueField: 'hodl',
      tooltip: 'Hodl BTC Profit Ratio: [bold]{valueY}%[/]',
    },
    {
      name: 'Bot Trading Profit',
      valueField: 'bot',
      tooltip: 'Bot Trading Profit Ratio: [bold]{valueY}%[/]',
    },
  ];

  const bots: Bot[] = (() => {
    const bots: Bot[] = [];
    for (let i = 0; i < 10; i++) {
      const bot = new Bot();
      console.log(bot.setId);
      bot.setId(i.toString());
      bot.setName(`Test Bot ${i}`);
      bots.push(bot);
    }
    return bots;
  })();

  const data: IData[] = (() => {
    let data: IData[] = [];
    const now = new Date();
    for (let i = 0; i < 365; i++) {
      const time = new Date(now.getTime());
      time.setDate(time.getDate() - i);
      data = data.concat({
        date: time,
        hodl: Math.cos(i / 12) * 100,
        bot: Math.sin(i / 12) * 100,
      });
    }
    return data;
  })();

  return (
    <>
      <section>
        <header className={style['dashboard-header']}>
          <h1>Dashboard</h1>
        </header>
        <OverAllGraph legend={legend} data={data} />
      </section>
      <section>
        <header className={style['dashboard-header']}>
          <h1>Bots</h1>
        </header>
        {
          bots.map((bot) => {
            return (<BotSummary bot={bot} />);
          })
        }
      </section>
    </>
  );
}

export default Dashboard;

// frontend/src/app/dashboard/dashboard.component.ts
import {
  Component,
  OnInit,
} from '@angular/core';

import { Bot } from '../rpc/bot_pb';
import { ISeries } from '../date-graph/date-graph.component'

interface IGraphData {
  date: Date,
  hodl: number,
  bot: number,
}

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {

  public botsInfo: Bot[];
  public data: IGraphData[];
  public readonly series: ISeries[] = [
    {
      name: 'Hodl BTC Profit',
      valueField: 'hodl',
      tooltip: 'Hodl BTC Profit Ratio: [bold]{valueY}%[/]',
    },
    {
      name: 'Bot Trading Profit',
      valueField: 'bot',
      tooltip: 'Bot Trading Profit Ratio: [bold]{valueY}%[/]',
    },
  ];

  constructor() {
    this.data = [];
    this.botsInfo = [];
    const now = new Date();
    for (let i = 0; i < 365; i++) {
      const time = new Date(now.getTime());
      time.setDate(time.getDate() - i);
      this.data.push({
        date: time,
        hodl: Math.cos(i / 12) * 100,
        bot: Math.sin(i / 12) * 100,
      });
    }
  }

  ngOnInit(): void {
    for (let i = 0; i < 5; i++) {
      const info = new Bot();
      info.setId(`test-bot-${i}`);
      info.setName(`Test Bot ${i}`);
      this.botsInfo = this.botsInfo.concat(info);
    }
  }
}

<div fxLayout="row">
  <div fxFlex="5vw"></div>
  <div fxFlex>
    <section class="dashboard">
      <header>
        <h1 i18n>Dashboard</h1>
      </header>
      <div id="compare-graph" class="graph"></div>
    </section>
  </div>
  <div fxFlex="5vw"></div>
</div>

<div fxLayout="row">
  <div fxFlex="5vw"></div>
  <div fxFlex>
    <section class="dashboard">
      <header>
        <h1 i18n>Bots</h1>
      </header>
      <mat-accordion>
        <app-bot-panel *ngFor="let bot of botsInfo" [bot]="bot"></app-bot-panel>
        <!-- <mat-expansion-panel *ngFor="let bot of botsInfo">
          <mat-expansion-panel-header>
            <mat-panel-title>{{ bot.getName() }}</mat-panel-title>
            <mat-panel-description>{{ bot.getDesc() }}</mat-panel-description>
          </mat-expansion-panel-header>
          <h2>Profit Graph</h2>
          <div class="graph" id="{{ bot.getId() }}"></div>
        </mat-expansion-panel> -->
      </mat-accordion>
    </section>
  </div>
  <div fxFlex="5vw"></div>
</div>
